/**
 * Configuration module for PSX Shariah Portfolio Tracker.
 *
 * Contains configuration constants for market data scraping,
 * caching, and Shariah index symbols.
 */

// Stock symbol with name
export interface StockInfo {
  symbol: string;
  name: string;
}

// KMI-30 Shariah-compliant index symbols (March 2026)
export const KMI_30_STOCKS: StockInfo[] = [
  { symbol: 'AIRLINK', name: 'Air Link Communication Limited' },
  { symbol: 'ATRL', name: 'Attock Refinery Limited' },
  { symbol: 'CNERGY', name: 'Cnergyico PK Limited' },
  { symbol: 'CPHL', name: 'Citi Pharma Ltd.' },
  { symbol: 'DGKC', name: 'D.G. Khan Cement Company Limited' },
  { symbol: 'EFERT', name: 'Engro Fertilizers Limited' },
  { symbol: 'ENGROH', name: 'Engro Holdings Limited' },
  { symbol: 'FCCL', name: 'Fauji Cement Company Limited' },
  { symbol: 'FFC', name: 'Fauji Fertilizer Company Limited' },
  { symbol: 'FFL', name: 'Fauji Foods Limited' },
  { symbol: 'GAL', name: 'Ghandhara Automobiles Limited' },
  { symbol: 'GHNI', name: 'Ghandhara Industries Limited' },
  { symbol: 'GLAXO', name: 'GlaxoSmithKline Pakistan Limited' },
  { symbol: 'HUBC', name: 'The Hub Power Company Limited' },
  { symbol: 'LUCK', name: 'Lucky Cement Limited' },
  { symbol: 'MARI', name: 'Mari Energies Limited' },
  { symbol: 'MEBL', name: 'Meezan Bank Limited' },
  { symbol: 'MLCF', name: 'Maple Leaf Cement Factory Limited' },
  { symbol: 'MTL', name: 'Millat Tractors Limited' },
  { symbol: 'NRL', name: 'National Refinery Limited' },
  { symbol: 'OGDC', name: 'Oil & Gas Development Company Limited' },
  { symbol: 'PAEL', name: 'Pak Elektron Limited' },
  { symbol: 'PPL', name: 'Pakistan Petroleum Limited' },
  { symbol: 'PRL', name: 'Pakistan Refinery Limited' },
  { symbol: 'PSO', name: 'Pakistan State Oil Company Limited' },
  { symbol: 'SAZEW', name: 'Sazgar Engineering Works Limited' },
  { symbol: 'SEARL', name: 'The Searle Company Limited' },
  { symbol: 'SNGP', name: 'Sui Northern Gas Pipelines Limited' },
  { symbol: 'SSGC', name: 'Sui Southern Gas Company Limited' },
  { symbol: 'SYS', name: 'Systems Limited' },
];

// KMI All Shares Index - Full Shariah-compliant universe (March 2026)
export const KMI_ALL_SHARES_STOCKS: StockInfo[] = [
  { symbol: 'AABS', name: 'Al-Abbas Sugar Mills Limited' },
  { symbol: 'ABOT', name: 'Abbott Laboratories (Pakistan) Limited' },
  { symbol: 'ACPL', name: 'Attock Cement Pakistan Limited' },
  { symbol: 'ADAMS', name: 'Adam Sugar Mills Limited' },
  { symbol: 'AGIL', name: 'Agriauto Industries Limited' },
  { symbol: 'AGP', name: 'AGP Limited' },
  { symbol: 'AGTL', name: 'Al-Ghazi Tractors Limited' },
  { symbol: 'AHTM', name: 'Ahmad Hassan Textile Mills Limited' },
  { symbol: 'AIRLINK', name: 'Air Link Communication Limited' },
  { symbol: 'AKDHL', name: 'AKD Hospitality Limited' },
  { symbol: 'AKGL', name: 'Al-Khair Gadoon Limited' },
  { symbol: 'ALNRS', name: 'Al-Noor Sugar Mills Limited' },
  { symbol: 'ANL', name: 'Azgard Nine Limited' },
  { symbol: 'ANTM', name: 'AN Textile Mills Limited' },
  { symbol: 'APL', name: 'Attock Petroleum Limited' },
  { symbol: 'ARCTM', name: 'Arctic Textile Mills Limited' },
  { symbol: 'ARPL', name: 'Archroma Pakistan Limited' },
  { symbol: 'ASHT', name: 'Ashfaq Textile Mills Limited' },
  { symbol: 'ASL', name: 'Aisha Steel Mills Limited' },
  { symbol: 'ATBA', name: 'Atlas Battery Limited' },
  { symbol: 'ATRL', name: 'Attock Refinery Limited' },
  { symbol: 'AVN', name: 'Avanceon Limited' },
  { symbol: 'AWTX', name: 'Allawasaya Tex. & Finishing Mills Ltd' },
  { symbol: 'BATA', name: 'Bata Pakistan Limited' },
  { symbol: 'BBFL', name: 'Big Bird Foods Limited' },
  { symbol: 'BCL', name: 'Bolan Castings Limited' },
  { symbol: 'BECO', name: 'Beco Steel Limited' },
  { symbol: 'BERG', name: 'Berger Paints Pakistan Limited' },
  { symbol: 'BFAGRO', name: 'Barkat Frisian Agro Limited' },
  { symbol: 'BFBIO', name: 'BF Biosciences Limited' },
  { symbol: 'BFMOD', name: 'B.F. Modaraba' },
  { symbol: 'BHAT', name: 'Bhanero Textile Mills Limited' },
  { symbol: 'BIFO', name: 'Biafo Industries Limited' },
  { symbol: 'BIPL', name: 'BankIslami Pakistan Limited' },
  { symbol: 'BLUEX', name: 'Blue-Ex Limited' },
  { symbol: 'BNL', name: 'Bunnys Limited' },
  { symbol: 'BNWM', name: 'Bannu Woollen Mills Limited' },
  { symbol: 'BPL', name: 'Burshane LPG (Pakistan) Limited' },
  { symbol: 'BRRG', name: 'B.R.R Guardian Limited' },
  { symbol: 'BTL', name: 'Blessed Textiles Limited' },
  { symbol: 'BUXL', name: 'Buxly Paints Limited' },
  { symbol: 'BWHL', name: 'Baluchistan Wheels Limited' },
  { symbol: 'CCM', name: 'Crescent Cotton Mills Limited' },
  { symbol: 'CEPB', name: 'Century Paper & Board Mills Limited' },
  { symbol: 'CFL', name: 'Crescent Fibres Limited' },
  { symbol: 'CHCC', name: 'Cherat Cement Company Limited' },
  { symbol: 'CLOV', name: 'Clover Pakistan Limited' },
  { symbol: 'CNERGY', name: 'Cnergyico PK Limited' },
  { symbol: 'CPHL', name: 'Citi Pharma Ltd.' },
  { symbol: 'CPPL', name: 'Cherat Packaging Limited' },
  { symbol: 'CRTM', name: 'The Crescent Textile Mills Limited' },
  { symbol: 'CSAP', name: 'Crescent Steel & Allied Products Limited' },
  { symbol: 'DAAG', name: 'Data Agro Limited' },
  { symbol: 'DADX', name: 'Dadex Eternit Limited' },
  { symbol: 'DCL', name: 'Dewan Cement Limited' },
  { symbol: 'DCR', name: 'Dolmen City REIT' },
  { symbol: 'DGKC', name: 'D.G. Khan Cement Company Limited' },
  { symbol: 'DIIL', name: 'Diamond Industries Limited' },
  { symbol: 'DINT', name: 'Din Textile Mills Limited' },
  { symbol: 'DMC', name: 'D.M. Corporation Limited' },
  { symbol: 'DNCC', name: 'Dandot Cement Company Limited' },
  { symbol: 'DOL', name: 'Descon Oxychem Limited' },
  { symbol: 'DYNO', name: 'Dynea Pakistan Limited' },
  { symbol: 'ECOP', name: 'Ecopack Limited' },
  { symbol: 'EFERT', name: 'Engro Fertilizers Limited' },
  { symbol: 'ELCM', name: 'Elahi Cotton Mills Limited' },
  { symbol: 'ELSM', name: 'Ellcot Spinning Mills Limited' },
  { symbol: 'EMCO', name: 'Emco Industries Limited' },
  { symbol: 'ENGROH', name: 'Engro Holdings Limited' },
  { symbol: 'EPCL', name: 'Engro Polymer & Chemicals Limited' },
  { symbol: 'EPQL', name: 'Engro Powergen Qadirpur Limited' },
  { symbol: 'EXIDE', name: 'Exide Pakistan Limited' },
  { symbol: 'FABL', name: 'Faysal Bank Limited' },
  { symbol: 'FANM', name: 'First Al-Noor Modaraba' },
  { symbol: 'FATIMA', name: 'Fatima Fertilizer Company Limited' },
  { symbol: 'FCCL', name: 'Fauji Cement Company Limited' },
  { symbol: 'FCEPL', name: 'Frieslandcampina Engro Pakistan Limited' },
  { symbol: 'FCL', name: 'Fast Cables Limited' },
  { symbol: 'FECM', name: 'First Elite Capital Modaraba' },
  { symbol: 'FECTC', name: 'Fecto Cement Limited' },
  { symbol: 'FEM', name: 'First Equity Modaraba' },
  { symbol: 'FEROZ', name: 'Ferozsons Laboratories Limited' },
  { symbol: 'FFC', name: 'Fauji Fertilizer Company Limited' },
  { symbol: 'FFL', name: 'Fauji Foods Limited' },
  { symbol: 'FFLM', name: 'First Fidelity Leasing Modaraba' },
  { symbol: 'FHAM', name: 'First Habib Modaraba' },
  { symbol: 'FIBLM', name: 'First IBL Modaraba' },
  { symbol: 'FIMM', name: 'First Imrooz Modaraba' },
  { symbol: 'FLYNG', name: 'Flying Cement Company Limited' },
  { symbol: 'FML', name: 'Feroze1888 Mills Limited' },
  { symbol: 'FPJM', name: 'First Punjab Modaraba' },
  { symbol: 'FPRM', name: 'First Paramount Modaraba' },
  { symbol: 'FRCL', name: 'Frontier Ceramics Limited' },
  { symbol: 'FRSM', name: 'Faran Sugar Mills Limited' },
  { symbol: 'FTMM', name: 'First Treet Manufacturing Modaraba' },
  { symbol: 'FTSM', name: 'First Tri-Star Modaraba' },
  { symbol: 'FZCM', name: 'Fazal Cloth Mills Limited' },
  { symbol: 'GAL', name: 'Ghandhara Automobiles Limited' },
  { symbol: 'GATI', name: 'Gatron (Industries) Limited' },
  { symbol: 'GATM', name: 'Gul Ahmed Textile Mills Limited' },
  { symbol: 'GCIL', name: 'Ghani Chemical Industries Limited' },
  { symbol: 'GCWL', name: 'Ghani Chemworld Limited' },
  { symbol: 'GDL', name: 'Ghani Dairies Limited' },
  { symbol: 'GEMBCEM', name: 'Burj Clean Energy Modaraba (GEM)' },
  { symbol: 'GEMMEL', name: 'Mughal Energy Limited (GEM)' },
  { symbol: 'GEMNETS', name: 'Nets International Communication Limited' },
  { symbol: 'GEMPACRA', name: 'The Pakistan Credit Rating Agency Ltd' },
  { symbol: 'GEMPAPL', name: 'Pak Agro Packaging Limited (GEM)' },
  { symbol: 'GEMSPNL', name: 'Supernet Limited' },
  { symbol: 'GFIL', name: 'Ghazi Fabrics International Limited' },
  { symbol: 'GGGL', name: 'Ghani Global Glass Limited' },
  { symbol: 'GGL', name: 'Ghani Global Holdings Limited' },
  { symbol: 'GHGL', name: 'Ghani Glass Limited' },
  { symbol: 'GHNI', name: 'Ghandhara Industries Limited' },
  { symbol: 'GIL', name: 'Good Luck Industries Ltd.' },
  { symbol: 'GLAXO', name: 'GlaxoSmithKline Pakistan Limited' },
  { symbol: 'GLPL', name: 'Gillette Pakistan Limited' },
  { symbol: 'GOC', name: 'GOC (Pak) Limited' },
  { symbol: 'GTYR', name: 'Ghandhara Tyre & Rubber Company Limited' },
  { symbol: 'GVGL', name: 'Ghani Value Glass Limited' },
  { symbol: 'GWLC', name: 'Gharibwal Cement Limited' },
  { symbol: 'HABSM', name: 'Habib Sugar Mills Limited' },
  { symbol: 'HAEL', name: 'Hala Enterprises Limited' },
  { symbol: 'HAFL', name: 'Hafiz Limited' },
  { symbol: 'HALEON', name: 'Haleon Pakistan Limited' },
  { symbol: 'HCAR', name: 'Honda Atlas Cars (Pakistan) Limited' },
  { symbol: 'HINO', name: 'Hinopak Motors Limited' },
  { symbol: 'HINOON', name: 'Highnoon Laboratories Limited' },
  { symbol: 'HPL', name: 'Hoechst Pakistan Limited' },
  { symbol: 'HRPL', name: 'Habib Rice Product Limited' },
  { symbol: 'HTL', name: 'Hi-Tech Lubricants Limited' },
  { symbol: 'HUBC', name: 'The Hub Power Company Limited' },
  { symbol: 'IBFL', name: 'Ibrahim Fibres Limited' },
  { symbol: 'IBLHL', name: 'IBL HealthCare Limited' },
  { symbol: 'ICCI', name: 'ICC Industries Limited' },
  { symbol: 'ICL', name: 'Ittehad Chemicals Limted' },
  { symbol: 'IDRT', name: 'Idrees Textile Mills Limited' },
  { symbol: 'IDSM', name: 'Ideal Spinning Mills Limited' },
  { symbol: 'ILP', name: 'Interloop Limited' },
  { symbol: 'IMAGE', name: 'Image Pakistan Limited' },
  { symbol: 'INIL', name: 'International Industries Limited' },
  { symbol: 'IPAK', name: 'International Packaging Films Limited' },
  { symbol: 'IREIT', name: 'Image Reit' },
  { symbol: 'ISIL', name: 'Ismail Industries Limited' },
  { symbol: 'ISL', name: 'International Steels Limited' },
  { symbol: 'ITTEFAQ', name: 'Ittefaq Iron Industries Limited' },
  { symbol: 'JDMT', name: 'Janana De Malucho Textile Mills Limited' },
  { symbol: 'JDWS', name: 'JDW Sugar Mills Limited' },
  { symbol: 'JKSM', name: 'J.K. Spinning Mills Limited' },
  { symbol: 'JSML', name: 'Jauharabad Sugar Mills Limited' },
  { symbol: 'JVDC', name: 'Javedan Corporation Limited' },
  { symbol: 'KCL', name: 'Karam Ceramics Limited' },
  { symbol: 'KEL', name: 'K-Electric Limited' },
  { symbol: 'KHYT', name: 'Khyber Textile Mills Limited' },
  { symbol: 'KML', name: 'Kohinoor Mills Limited' },
  { symbol: 'KOHC', name: 'Kohat Cement Company Limited' },
  { symbol: 'KOHE', name: 'Kohinoor Energy Limited' },
  { symbol: 'KOHTM', name: 'Kohat Textile Mills Limited' },
  { symbol: 'KPUS', name: 'Khairpur Sugar Mills Limited' },
  { symbol: 'KSBP', name: 'KSB Pumps Company Limited' },
  { symbol: 'KTML', name: 'Kohinoor Textile Mills Limited' },
  { symbol: 'LCI', name: 'Lucky Core Industries Limited' },
  { symbol: 'LEUL', name: 'Leather Up Limited' },
  { symbol: 'LIVEN', name: 'Liven Pharma Limited' },
  { symbol: 'LOADS', name: 'Loads Limited' },
  { symbol: 'LOTCHEM', name: 'Lotte Chemical Pakistan Limited' },
  { symbol: 'LPGL', name: 'Leiner Pak Gelatine Limited' },
  { symbol: 'LUCK', name: 'Lucky Cement Limited' },
  { symbol: 'MACFL', name: 'MACPAC Films Limited' },
  { symbol: 'MACTER', name: 'Macter International Limited' },
  { symbol: 'MARI', name: 'Mari Energies Limited' },
  { symbol: 'MEBL', name: 'Meezan Bank Limited' },
  { symbol: 'MEHT', name: 'Mehmood Textile Mills Limited' },
  { symbol: 'MERIT', name: 'Merit Packaging Limited' },
  { symbol: 'MFFL', name: 'Mitchells Fruit Farms Limited' },
  { symbol: 'MFL', name: 'Matco Foods Limited' },
  { symbol: 'MLCF', name: 'Maple Leaf Cement Factory Limited' },
  { symbol: 'MQTM', name: 'Maqbool Textile Mills Limited' },
  { symbol: 'MSCL', name: 'Metropolitan Steel Corporation Limited' },
  { symbol: 'MTL', name: 'Millat Tractors Limited' },
  { symbol: 'MUGHAL', name: 'Mughal Iron & Steel Industries Limited' },
  { symbol: 'MWMP', name: 'Mandviwala Mauser Plastic Industries' },
  { symbol: 'NATF', name: 'National Foods Limited' },
  { symbol: 'NATM', name: 'Nadeem Textile Mills Limited' },
  { symbol: 'NESTLE', name: 'Nestle Pakistan Limited' },
  { symbol: 'NETSOL', name: 'NetSol Technologies Limited' },
  { symbol: 'NML', name: 'Nishat Mills Limited' },
  { symbol: 'NRL', name: 'National Refinery Limited' },
  { symbol: 'NRSL', name: 'Nimir Resins Limited' },
  { symbol: 'NSRM', name: 'The National Silk & Rayon Mills Limited' },
  { symbol: 'OBOY', name: 'Oilboy Energy Limited' },
  { symbol: 'OCTOPUS', name: 'Octopus Digital Limited' },
  { symbol: 'OGDC', name: 'Oil & Gas Development Company Limited' },
  { symbol: 'OLPM', name: 'OLP Modaraba' },
  { symbol: 'OML', name: 'Olympia Mills Limited' },
  { symbol: 'ORM', name: 'Orient Rental Mod' },
  { symbol: 'PAEL', name: 'Pak Elektron Limited' },
  { symbol: 'PAKD', name: 'Pak Datacom Limited' },
  { symbol: 'PAKOXY', name: 'Pakistan Oxygen Limited' },
  { symbol: 'PAKQATAR', name: 'Pak Qatar Family Takaful Limited' },
  { symbol: 'PIBTL', name: 'Pakistan International Bulk Terminal' },
  { symbol: 'PIM', name: 'Popular Islamic Modaraba' },
  { symbol: 'PIOC', name: 'Pioneer Cement Limited' },
  { symbol: 'PKGS', name: 'Packages Limited' },
  { symbol: 'POML', name: 'Punjab Oil Mills Limited' },
  { symbol: 'POWER', name: 'Power Cement Limited' },
  { symbol: 'PPL', name: 'Pakistan Petroleum Limited' },
  { symbol: 'PPP', name: 'Pakistan Paper Products Limited' },
  { symbol: 'PQGTL', name: 'Pak Qatar General Takaful Limited' },
  { symbol: 'PREMA', name: 'At-Tahur Limited' },
  { symbol: 'PRL', name: 'Pakistan Refinery Limited' },
  { symbol: 'PSEL', name: 'Pakistan Services Limited' },
  { symbol: 'PSO', name: 'Pakistan State Oil Company Limited' },
  { symbol: 'PSYL', name: 'Pakistan Synthetics Limited' },
  { symbol: 'PTL', name: 'Panther Tyres Ltd.' },
  { symbol: 'QUICE', name: 'Quice Food Industries Limited' },
  { symbol: 'RCML', name: 'Reliance Cotton Spinning Mills Limited' },
  { symbol: 'REDCO', name: 'Redco Textiles Limited' },
  { symbol: 'REWM', name: 'Reliance Weaving Mills Limited' },
  { symbol: 'RMPL', name: 'Rafhan Maize Products Company Limited' },
  { symbol: 'RPL', name: 'Roshan Packages Limited' },
  { symbol: 'RUPL', name: 'Rupali Polyester Limited' },
  { symbol: 'SAIF', name: 'Saif Textile Mills Limited' },
  { symbol: 'SANSM', name: 'Sanghar Sugar Mills Limited' },
  { symbol: 'SAPT', name: 'Sapphire Textile Mills Limited' },
  { symbol: 'SARC', name: 'Sardar Chemical Industries Limited' },
  { symbol: 'SAZEW', name: 'Sazgar Engineering Works Limited' },
  { symbol: 'SCL', name: 'Shield Corporation Limited' },
  { symbol: 'SEARL', name: 'The Searle Company Limited' },
  { symbol: 'SEL', name: 'Sitara Energy Limited' },
  { symbol: 'SERT', name: 'Service Industries Textiles Limited' },
  { symbol: 'SGF', name: 'Service GlobalFootwear Limited' },
  { symbol: 'SGPL', name: 'S.G. Power Limited' },
  { symbol: 'SHCM', name: 'Shadman Cotton Mills Limited' },
  { symbol: 'SHDT', name: 'Shadab Textile Mills Limited' },
  { symbol: 'SHEZ', name: 'Shezan International Limited' },
  { symbol: 'SHFA', name: 'Shifa International Hospitals Limited' },
  { symbol: 'SHSML', name: 'Shahmurad Sugar Mills Limited' },
  { symbol: 'SIEM', name: 'Siemens (Pakistan) Engineering' },
  { symbol: 'SINDM', name: 'Sindh Modaraba' },
  { symbol: 'SITC', name: 'Sitara Chemical Industries Limited' },
  { symbol: 'SLGL', name: 'Secure Logistics-Trax Group Limited' },
  { symbol: 'SMCPL', name: 'Safe Mix Concrete Limited' },
  { symbol: 'SNAI', name: 'Sana Industries Limited' },
  { symbol: 'SNGP', name: 'Sui Northern Gas Pipelines Limited' },
  { symbol: 'SPEL', name: 'SPEL Limited' },
  { symbol: 'SPWL', name: 'Saif Power Limited' },
  { symbol: 'SRR', name: 'Signature Residency Reit' },
  { symbol: 'SSGC', name: 'Sui Southern Gas Company Limited' },
  { symbol: 'SSOM', name: 'S.S.Oil Mills Limited' },
  { symbol: 'STCL', name: 'Shabbir Tiles & Ceramics Limited' },
  { symbol: 'STJT', name: 'Shahtaj Textile Limited' },
  { symbol: 'STL', name: 'Supernet Technologies Limited' },
  { symbol: 'STML', name: 'Shams Textile Mills Limited' },
  { symbol: 'STYLERS', name: 'Stylers International Limited' },
  { symbol: 'SURC', name: 'Suraj Cotton Mills Limited' },
  { symbol: 'SYM', name: 'Symmetry Group Limited' },
  { symbol: 'SYS', name: 'Systems Limited' },
  { symbol: 'SZTM', name: 'Shahzad Textile Mills Limited' },
  { symbol: 'TATM', name: 'Tata Textile Mills Limited' },
  { symbol: 'TBL', name: 'Treet Battery Limited' },
  { symbol: 'TCORP', name: 'Tariq Corporation Limited' },
  { symbol: 'TELE', name: 'Telecard Limited' },
  { symbol: 'TGL', name: 'Tariq Glass Industries Limited' },
  { symbol: 'TICL', name: 'The Thal Industries Corporation Limited' },
  { symbol: 'TOMCL', name: 'The Organic Meat Company Limited' },
  { symbol: 'TOWL', name: 'Towellers Limited' },
  { symbol: 'TPLP', name: 'TPL Properties Limited' },
  { symbol: 'TPLRF1', name: 'TPL REIT Fund I' },
  { symbol: 'TPLT', name: 'TPL Trakker Limited' },
  { symbol: 'TREET', name: 'Treet Corporation Limited' },
  { symbol: 'TRSM', name: 'Trust Modaraba' },
  { symbol: 'UBDL', name: 'United Brands Limited' },
  { symbol: 'UCAPM', name: 'Unicap Modaraba' },
  { symbol: 'UDLI', name: 'UDL International Limited' },
  { symbol: 'UDPL', name: 'United Distributors Pakistan Limited' },
  { symbol: 'UPFL', name: 'Unilever Pakistan Foods Limited' },
  { symbol: 'WAFI', name: 'Wafi Energy Pakistan Limited' },
  { symbol: 'WAHN', name: 'Wah Noble Chemicals Limited' },
  { symbol: 'WASL', name: 'Wasl Mobility Modaraba' },
  { symbol: 'WAVES', name: 'Waves Corporation Limited' },
  { symbol: 'YOUW', name: 'Yousaf Weaving Mills Limited' },
  { symbol: 'ZAHID', name: 'Zahidjee Textile Mills Limited' },
  { symbol: 'ZAL', name: 'Zarea Limited' },
  { symbol: 'ZIL', name: 'ZIL Limited' },
  { symbol: 'ZTL', name: 'Zephyr Textiles Limited' },
];

// Legacy export for backward compatibility
export const KMI_30_SYMBOLS = KMI_30_STOCKS.map(s => s.symbol) as readonly string[];

// All KMI All Shares symbols
export const KMI_ALL_SHARES_SYMBOLS = KMI_ALL_SHARES_STOCKS.map(s => s.symbol);

// Helper to get stock name by symbol
export function getStockName(symbol: string): string | undefined {
  const upperSymbol = symbol.toUpperCase();
  const stock = KMI_ALL_SHARES_STOCKS.find(s => s.symbol === upperSymbol);
  return stock?.name;
}

// Helper to check if symbol is in KMI-30
export function isKmi30(symbol: string): boolean {
  return KMI_30_SYMBOLS.includes(symbol.toUpperCase());
}

// Helper to check if symbol is Shariah-compliant (in KMI All Shares)
export function isShariahCompliant(symbol: string): boolean {
  return KMI_ALL_SHARES_SYMBOLS.includes(symbol.toUpperCase());
}

// Index types
export type IndexType = 'KMI30' | 'KMIALLSHR';

// Cache duration settings (in seconds)
export const CACHE_DURATION = {
  market_watch: 15, // 15 seconds - real-time updates via PSX Terminal
  eod: 86400, // 24 hours - for end-of-day historical data
  fundamentals: 86400, // 24 hours - for company fundamentals
} as const;

// PSX market hours configuration (Pakistan Standard Time - Asia/Karachi)
export const PSX_MARKET_HOURS = {
  start: '09:30', // Market opens at 9:30 AM
  end: '15:30', // Market closes at 3:30 PM
  timezone: 'Asia/Karachi',
} as const;

// User-Agent header for HTTP requests to PSX servers
export const USER_AGENT =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
